package net.omniblock.shop.api.type;

import org.bukkit.Material;

@SuppressWarnings("deprecation")
public enum AdminShopItem {

	
	/*
	 * > Type: Block items
	 */
	STONE(KindItem.BUILDING_BLOCKS, Material.STONE, 35, 10),
	GRANITE(KindItem.BUILDING_BLOCKS, Material.STONE, 1, 35, 15),
	POLISHE_DGRANITE(KindItem.BUILDING_BLOCKS, Material.STONE, 2, 35, 10),
	DIORITE(KindItem.BUILDING_BLOCKS, Material.STONE, 3, 50, 15),
	POLISHED_DIORITE(KindItem.BUILDING_BLOCKS, Material.STONE, 4, 35, 10),
	ANDESITE(KindItem.BUILDING_BLOCKS, Material.STONE, 5, 35, 15),
	POLISHED_ANDESITE(KindItem.BUILDING_BLOCKS, Material.STONE, 6, 35, 10),
	GRASS(KindItem.BUILDING_BLOCKS, Material.GRASS, 35, 10),
	DIRT(KindItem.BUILDING_BLOCKS, Material.DIRT, 35, 10),
	COARSE_DIRT(KindItem.BUILDING_BLOCKS, Material.DIRT, 1, 35, 10),
	PODZOL(KindItem.BUILDING_BLOCKS, Material.DIRT, 2, 35, 10),
	COBBLESTONE(KindItem.BUILDING_BLOCKS, Material.COBBLESTONE, 5, 1),
	WOOD(KindItem.BUILDING_BLOCKS, Material.WOOD, 5, 1),
	SPRUCE_WOOD(KindItem.BUILDING_BLOCKS, Material.WOOD, 1, 5, 1),
	BIRCH_WOOD(KindItem.BUILDING_BLOCKS, Material.WOOD, 2, 5, 1),
	JUNGLE_WOOD(KindItem.BUILDING_BLOCKS, Material.WOOD, 3, 5, 1),
	ACACIA_WOOD(KindItem.BUILDING_BLOCKS, Material.WOOD, 4, 5, 1),
	DARK_WOOD(KindItem.BUILDING_BLOCKS, Material.WOOD, 5, 5, 1),
	SAND(KindItem.BUILDING_BLOCKS, Material.SAND, 5, 1),
	RED_SAND(KindItem.BUILDING_BLOCKS, Material.SAND, 1, 20, 5),
	GRAVEL(KindItem.BUILDING_BLOCKS, Material.GRAVEL, 20, 10),
	GOLD_ORE(KindItem.BUILDING_BLOCKS, Material.GOLD_ORE, 140, 70),
	REDSTONE_ORE(KindItem.BUILDING_BLOCKS, Material.REDSTONE_ORE, 100, 50),
	IRON_ORE(KindItem.BUILDING_BLOCKS, Material.IRON_ORE, 120, 60),
	LAPIS_ORE(KindItem.BUILDING_BLOCKS, Material.LAPIS_ORE, 100, 50),
	COAL_ORE(KindItem.BUILDING_BLOCKS, Material.COAL_ORE, 20, 10),
	EMERALD_ORE(KindItem.BUILDING_BLOCKS, Material.EMERALD_ORE, 300, 150),
	DIAMOND_ORE(KindItem.BUILDING_BLOCKS, Material.DIAMOND_ORE, 200, 100),
	LOG(KindItem.BUILDING_BLOCKS, Material.LOG, 10, 5),
	SPRUCE_LOG(KindItem.BUILDING_BLOCKS, Material.WOOD, 1, 10, 5),
	BIRCH_LOG(KindItem.BUILDING_BLOCKS, Material.WOOD, 2, 10, 5),
	JUNGLE_LOG(KindItem.BUILDING_BLOCKS, Material.WOOD, 3, 10, 5),
	SPONGE(KindItem.BUILDING_BLOCKS, Material.SPONGE, 40, 20),
	WET_SPONGE(KindItem.BUILDING_BLOCKS, Material.SPONGE, 1, 300, 15),
	GLASS(KindItem.BUILDING_BLOCKS, Material.GLASS, 15, 5),
	LAPIS_BLOCK(KindItem.BUILDING_BLOCKS, Material.LAPIS_BLOCK, 270, 135),
	SAND_STONE(KindItem.BUILDING_BLOCKS, Material.SANDSTONE, 40, 20),
	CHISELED_SAND_STONE(KindItem.BUILDING_BLOCKS, Material.SANDSTONE, 1, 40, 20),
	SMOOTH_SAND_STONE(KindItem.BUILDING_BLOCKS, Material.SANDSTONE, 2, 40, 20),
	WHITE_WOOL(KindItem.BUILDING_BLOCKS, Material.WOOL, 20, 10),
	ORANGE_WOOL(KindItem.BUILDING_BLOCKS, Material.WOOL, 1, 50, 10),
	MAGENTA_WOOL(KindItem.BUILDING_BLOCKS, Material.WOOL, 2, 50, 10),
	LIGHT_BLUE_WOOL(KindItem.BUILDING_BLOCKS, Material.WOOL, 3, 50, 10),
	YELLOW_WOOL(KindItem.BUILDING_BLOCKS, Material.WOOL, 4, 35, 10),
	LIME_WOOL(KindItem.BUILDING_BLOCKS, Material.WOOL, 5, 35, 10),
	PINK_WOOL(KindItem.BUILDING_BLOCKS, Material.WOOL, 6, 35, 10),
	GRAY_WOOL(KindItem.BUILDING_BLOCKS, Material.WOOL, 7, 35, 10),
	LIGHT_GRAY_WOOL(KindItem.BUILDING_BLOCKS, Material.WOOL, 8, 35, 10),
	CYAN_WOOL(KindItem.BUILDING_BLOCKS, Material.WOOL, 9, 35, 10),
	PURPLE_WOOL(KindItem.BUILDING_BLOCKS, Material.WOOL, 10, 35, 10),
	BLUE_WOOL(KindItem.BUILDING_BLOCKS, Material.WOOL, 11, 35, 10),
	BROWN_WOOL(KindItem.BUILDING_BLOCKS, Material.WOOL, 12, 35, 10),
	GREEN_WOOL(KindItem.BUILDING_BLOCKS, Material.WOOL, 13, 35, 10),
	RED_WOOL(KindItem.BUILDING_BLOCKS, Material.WOOL, 14, 35, 10),
	GOLD_BLOCK(KindItem.BUILDING_BLOCKS, Material.GOLD_BLOCK, 450, 220),
	IRON_BLOCK(KindItem.BUILDING_BLOCKS, Material.IRON_BLOCK, 450, 230),
	STONE_SLAB(KindItem.BUILDING_BLOCKS, Material.getMaterial(44), 40, 20),
	SAND_SLAB(KindItem.BUILDING_BLOCKS, Material.getMaterial(44), 1, 40, 20),
	COBBLESTONE_SLAB(KindItem.BUILDING_BLOCKS, Material.getMaterial(44), 3, 40, 20),
	BRICKS_SLAB(KindItem.BUILDING_BLOCKS, Material.getMaterial(44), 4, 40, 20),
	STONE_BRICKS_SLAB(KindItem.BUILDING_BLOCKS, Material.getMaterial(44), 5, 40, 20),
	NETHER_BRICK_SALB(KindItem.BUILDING_BLOCKS, Material.getMaterial(44), 6, 40, 20),
	QUARTZ_SLAB(KindItem.BUILDING_BLOCKS, Material.getMaterial(44), 7, 40, 20),
	BRICK(KindItem.BUILDING_BLOCKS, Material.BRICK, 60, 30),
	BOOK_SHELF(KindItem.BUILDING_BLOCKS, Material.BOOKSHELF, 80, 40),
	MOSSY_COBBLESTONE(KindItem.BUILDING_BLOCKS, Material.MOSSY_COBBLESTONE, 115, 62),
	OBSIDIAN(KindItem.BUILDING_BLOCKS, Material.OBSIDIAN, 64, 32),
	WOOD_STAIRS(KindItem.BUILDING_BLOCKS, Material.WOOD_STAIRS, 30, 15),
	STONE_STAIRS(KindItem.BUILDING_BLOCKS, Material.COBBLESTONE_STAIRS, 30, 15),
	ICE(KindItem.BUILDING_BLOCKS, Material.ICE, 200, 25),
	SNOW(KindItem.BUILDING_BLOCKS, Material.SNOW, 60, 30),
	CLAY(KindItem.BUILDING_BLOCKS, Material.CLAY, 100, 25),
	PUMPKIN(KindItem.BUILDING_BLOCKS, Material.PUMPKIN, 80, 40),
	NETHER_RACK(KindItem.BUILDING_BLOCKS, Material.NETHERRACK, 50, 10),
	SOUL_SAND(KindItem.BUILDING_BLOCKS, Material.SOUL_SAND, 140, 70),
	GLOWSTONE(KindItem.BUILDING_BLOCKS, Material.GLOWSTONE, 200, 25),
	LIT_PUMPKIN(KindItem.BUILDING_BLOCKS, Material.getMaterial(91), 80, 40),
	WHITE_GLASS(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS, 25, 10),
	ORANGE_GLASS(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS, 1, 60, 10),
	MAGENTA_GLASS(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS, 2, 60, 10),
	LIGHT_BLUE_GLASS(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS, 3, 60, 10),
	YELLOW_GLASS(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS, 4, 60, 10),
	LIME_GLASS(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS, 5, 60, 10),
	PINK_GLASS(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS, 6, 60, 10),
	GRAY_GLASS(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS, 7, 60, 10),
	LIGHT_GRAY_GLASS(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS, 8, 60, 10),
	CYAN_GLASS(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS, 9, 60, 10),
	PURPLE_GLASS(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS, 10, 60, 10),
	BLUE_GLASS(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS, 11, 60, 10),
	BROWN_GLASS(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS, 12, 60, 10),
	GREEN_GLASS(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS, 13, 60, 10),
	RED_GLASS(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS, 14, 60, 10),
	BLACK_GLASS(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS, 15, 60, 10),
	STONE_BRICKS(KindItem.BUILDING_BLOCKS, Material.BRICK, 80, 40),
	MOSSY_BRICKS(KindItem.BUILDING_BLOCKS, Material.BRICK, 1, 80, 40),
	CRACKED_BRICKS(KindItem.BUILDING_BLOCKS, Material.BRICK, 2, 80, 40),
	CHISELED_BRICKS(KindItem.BUILDING_BLOCKS, Material.BRICK, 3, 80, 40),
	MELON_BLOCK(KindItem.BUILDING_BLOCKS, Material.MELON_BLOCK, 800, 400),
	BRICK_STAIRS(KindItem.BUILDING_BLOCKS, Material.BRICK_STAIRS, 30, 15),
	STONE_BRICK_STAIRS(KindItem.BUILDING_BLOCKS, Material.BRICK_STAIRS, 30,15),
	MYCELIUM(KindItem.BUILDING_BLOCKS, Material.getMaterial(110), 200, 100),
	NETHER_BRICK(KindItem.BUILDING_BLOCKS, Material.NETHER_BRICK, 100, 50),
	NETHER_BRICK_STAIRS(KindItem.BUILDING_BLOCKS, Material.NETHER_BRICK_STAIRS, 30, 15),
	END_STONE(KindItem.BUILDING_BLOCKS, Material.ENDER_STONE, 20, 10),
	WOOD_SLAB(KindItem.BUILDING_BLOCKS, Material.getMaterial(126), 35, 15),
	SPRUCE_WOOD_SLAB(KindItem.BUILDING_BLOCKS, Material.getMaterial(126), 1, 35, 15),
	BIRCH_WOOD_SLAB(KindItem.BUILDING_BLOCKS, Material.getMaterial(126), 2, 35, 15),
	JUNGLE_WOOD_SLAB(KindItem.BUILDING_BLOCKS, Material.getMaterial(126), 3, 35, 15),
	ACACIA_WOOD_SLAB(KindItem.BUILDING_BLOCKS, Material.getMaterial(126), 4, 35, 15),
	DARK_WOOD_SLAB(KindItem.BUILDING_BLOCKS, Material.getMaterial(126), 5, 35, 15),
	SANDSTONE_STAIRS(KindItem.BUILDING_BLOCKS, Material.SANDSTONE_STAIRS, 35, 15),
	EMERALD_BLOCK(KindItem.BUILDING_BLOCKS, Material.EMERALD_BLOCK, 400, 234),
	SPRUCE_WOOD_STAIRS(KindItem.BUILDING_BLOCKS, Material.SPRUCE_WOOD_STAIRS, 35, 15),
	BRICH_WOOD_STAIRS(KindItem.BUILDING_BLOCKS, Material.BIRCH_WOOD_STAIRS, 35, 15),
	JUNGLA_WOOD_STAIRS(KindItem.BUILDING_BLOCKS, Material.JUNGLE_WOOD_STAIRS, 35, 15),
	QUARTZ_ORE(KindItem.BUILDING_BLOCKS, Material.QUARTZ_ORE, 100, 50),
	QUARTZ_BLOCK(KindItem.BUILDING_BLOCKS, Material.QUARTZ_BLOCK, 200, 100),
	CHISELED_QUARTZ_BLOCK(KindItem.BUILDING_BLOCKS, Material.QUARTZ_BLOCK, 1, 200, 100),
	PILLAR_QUARTZ_BLOCK(KindItem.BUILDING_BLOCKS, Material.QUARTZ_BLOCK,2, 200, 100),
	QUARTZ_STAIRS(KindItem.BUILDING_BLOCKS, Material.QUARTZ_STAIRS, 35, 15),
	WHITE_CLAY(KindItem.BUILDING_BLOCKS, Material.STAINED_CLAY, 50, 25),
	ORANGE_CLAY(KindItem.BUILDING_BLOCKS, Material.STAINED_CLAY, 1, 50, 25),
	MAGENTA_CLAY(KindItem.BUILDING_BLOCKS, Material.STAINED_CLAY, 2, 50, 25),
	LIGHT_BLUE_CLAY(KindItem.BUILDING_BLOCKS, Material.STAINED_CLAY, 3, 50, 25),
	YELLOW_CLAY(KindItem.BUILDING_BLOCKS, Material.STAINED_CLAY, 4, 50, 25),
	LIME_CLAY(KindItem.BUILDING_BLOCKS, Material.STAINED_CLAY, 5, 50, 25),
	PINK_CLAY(KindItem.BUILDING_BLOCKS, Material.STAINED_CLAY, 6, 50, 25),
	GRAY_CLAY(KindItem.BUILDING_BLOCKS, Material.STAINED_CLAY, 7, 50, 25),
	LIGHT_GRAY_CLAY(KindItem.BUILDING_BLOCKS, Material.STAINED_CLAY, 8, 50, 25),
	CYAN_CLAY(KindItem.BUILDING_BLOCKS, Material.STAINED_CLAY, 9, 50, 25),
	PURPLE_CLAY(KindItem.BUILDING_BLOCKS, Material.STAINED_CLAY, 10, 50, 25),
	BLUE_CLAY(KindItem.BUILDING_BLOCKS, Material.STAINED_CLAY, 11, 50, 25),
	BROWN_CLAY(KindItem.BUILDING_BLOCKS, Material.STAINED_CLAY, 12, 50, 25),
	GREEN_CLAY(KindItem.BUILDING_BLOCKS, Material.STAINED_CLAY, 13, 50, 25),
	RED_CLAY(KindItem.BUILDING_BLOCKS, Material.STAINED_CLAY, 14, 50, 25),
	BLACK_CLAY(KindItem.BUILDING_BLOCKS, Material.STAINED_CLAY, 15, 50, 25),
	ACACIA_LOG2(KindItem.BUILDING_BLOCKS, Material.LOG_2, 5, 1),
	DARK_LOG2(KindItem.BUILDING_BLOCKS, Material.LOG_2, 1, 5, 1),
	ACACIA_WOOD_STAIRS(KindItem.BUILDING_BLOCKS, Material.ACACIA_STAIRS, 35, 15),
	DARK_WOOD_STAIRS(KindItem.BUILDING_BLOCKS, Material.DARK_OAK_STAIRS, 35, 15),
	PRISMARINE(KindItem.BUILDING_BLOCKS, Material.PRISMARINE, 400, 200),
	PRISMARINE_BRICKS(KindItem.BUILDING_BLOCKS, Material.PRISMARINE, 1, 400, 200),
	DARK_PRISMARINE(KindItem.BUILDING_BLOCKS, Material.PRISMARINE, 2, 400, 200),
	SEA_LANTERN(KindItem.BUILDING_BLOCKS, Material.SEA_LANTERN, 400, 200),
	HAY_BLOCK(KindItem.BUILDING_BLOCKS, Material.HAY_BLOCK, 100, 500),
	HARDENED_CLAY(KindItem.BUILDING_BLOCKS, Material.HARD_CLAY, 50, 25),
	COAL_BLOCK(KindItem.BUILDING_BLOCKS, Material.COAL_BLOCK, 180, 90),
	PACKED_ICE(KindItem.BUILDING_BLOCKS, Material.PACKED_ICE, 400, 40),
	RED_SANDSTONE(KindItem.BUILDING_BLOCKS, Material.RED_SANDSTONE, 20, 10),
	CHISELED_RED_SANDSTONE(KindItem.BUILDING_BLOCKS, Material.RED_SANDSTONE, 1, 20, 10),
	SMOOTH_RED_SANDSTONE(KindItem.BUILDING_BLOCKS, Material.RED_SANDSTONE, 2, 20, 10),
	RED_SANDSTONE_STAIRS(KindItem.BUILDING_BLOCKS, Material.RED_SANDSTONE_STAIRS, 35, 15),
	RED_SANDSTONE_SLAB(KindItem.BUILDING_BLOCKS, Material.getMaterial(182), 35, 15),
	PURPUR_BLOCK(KindItem.BUILDING_BLOCKS, Material.PURPUR_BLOCK, 100, 50),
	PURPUR_PILLAR(KindItem.BUILDING_BLOCKS, Material.PURPUR_PILLAR, 100, 500),
	PURPUR_STAIRS(KindItem.BUILDING_BLOCKS, Material.PURPUR_STAIRS, 35, 15),
	PURPUR_SLAB(KindItem.BUILDING_BLOCKS, Material.PURPUR_SLAB, 35, 15),
	END_BRICKS(KindItem.BUILDING_BLOCKS, Material.END_BRICKS, 100, 50),
	MAGMA_BLOCK(KindItem.BUILDING_BLOCKS, Material.MAGMA, 100, 50),
	NETHER_WART_BLOCK(KindItem.BUILDING_BLOCKS, Material.NETHER_WART_BLOCK, 100, 50),
	RED_NETHER_BRICK(KindItem.BUILDING_BLOCKS, Material.RED_NETHER_BRICK, 100, 50),
	BONE_BLOCK(KindItem.BUILDING_BLOCKS, Material.BONE_BLOCK, 50, 25),
	WHITE_CONCRETE(KindItem.BUILDING_BLOCKS, Material.CONCRETE, 20, 10),
	ORANGE_CONCRETE(KindItem.BUILDING_BLOCKS, Material.CONCRETE, 1, 20, 10),
	MAGENTA_CONCRETE(KindItem.BUILDING_BLOCKS, Material.CONCRETE, 2, 20, 10),
	LIGHT_BLUE_CONCRETE(KindItem.BUILDING_BLOCKS, Material.CONCRETE, 3, 20, 10),
	YELLOW_CONCRETE(KindItem.BUILDING_BLOCKS, Material.CONCRETE, 4, 20, 10),
	LIME_CONCRETE(KindItem.BUILDING_BLOCKS, Material.CONCRETE, 5, 20, 10),
	PINK_CONCRETE(KindItem.BUILDING_BLOCKS, Material.CONCRETE, 6, 20, 10),
	GRAY_CONCRETE(KindItem.BUILDING_BLOCKS, Material.CONCRETE, 7, 20, 10),
	LIGHT_GRAY_CONCRETE(KindItem.BUILDING_BLOCKS, Material.CONCRETE, 8, 20, 10),
	CYAN_CONCRETE(KindItem.BUILDING_BLOCKS, Material.CONCRETE, 9, 20, 10),
	PURPLE_CONCRETE(KindItem.BUILDING_BLOCKS, Material.CONCRETE, 10, 20, 10),
	BLUE_CONCRETE(KindItem.BUILDING_BLOCKS, Material.CONCRETE, 11, 20, 10),
	BROWN_CONCRETE(KindItem.BUILDING_BLOCKS, Material.CONCRETE, 12, 20, 10),
	GREEN_CONCRETE(KindItem.BUILDING_BLOCKS, Material.CONCRETE, 13, 20, 10),
	RED_CONCRETE(KindItem.BUILDING_BLOCKS, Material.CONCRETE, 14, 20, 10),
	BLACK_CONCRETE(KindItem.BUILDING_BLOCKS, Material.CONCRETE, 15, 20, 10),
	WHITE_CONCRETE_POWDER(KindItem.BUILDING_BLOCKS, Material.CONCRETE_POWDER, 100, 40),
	ORANGE_CONCRETE_POWDER(KindItem.BUILDING_BLOCKS, Material.CONCRETE_POWDER, 1, 100, 40),
	MAGENTA_CONCRETE_POWDER(KindItem.BUILDING_BLOCKS, Material.CONCRETE_POWDER, 2, 100, 40),
	LIGHT_BLUE_CONCRETE_POWDER(KindItem.BUILDING_BLOCKS, Material.CONCRETE_POWDER, 3, 100, 40),
	YELLOW_CONCRETE_POWDER(KindItem.BUILDING_BLOCKS, Material.CONCRETE_POWDER, 4, 100, 40),
	LIME_CONCRETE_POWDER(KindItem.BUILDING_BLOCKS, Material.CONCRETE_POWDER, 5, 100, 40),
	PINK_CONCRETE_POWDER(KindItem.BUILDING_BLOCKS, Material.CONCRETE_POWDER, 6, 100, 40),
	GRAY_CONCRETE_POWDER(KindItem.BUILDING_BLOCKS, Material.CONCRETE_POWDER, 7, 100, 40),
	LIGHT_GRAY_CONCRETE_POWDER(KindItem.BUILDING_BLOCKS, Material.CONCRETE_POWDER, 8, 100, 40),
	CYAN_CONCRETE_POWDER(KindItem.BUILDING_BLOCKS, Material.CONCRETE_POWDER, 9, 100, 40),
	PURPLE_CONCRETE_POWDER(KindItem.BUILDING_BLOCKS, Material.CONCRETE_POWDER, 10, 100, 40),
	BLUE_CONCRETE_POWDER(KindItem.BUILDING_BLOCKS, Material.CONCRETE_POWDER, 11, 100, 40),
	BROWN_CONCRETE_POWDER(KindItem.BUILDING_BLOCKS, Material.CONCRETE_POWDER, 12, 100, 40),
	GREEN_CONCRETE_POWDER(KindItem.BUILDING_BLOCKS, Material.CONCRETE_POWDER, 13, 100, 40),
	RED_CONCRETE_POWDER(KindItem.BUILDING_BLOCKS, Material.CONCRETE_POWDER, 14, 100, 40),
	BLACK_CONCRETE_POWDER(KindItem.BUILDING_BLOCKS, Material.CONCRETE_POWDER, 15, 100, 40),
	CHEST(KindItem.BUILDING_BLOCKS, Material.CHEST, 20, 10),
	CRAFTING_tABLE(KindItem.BUILDING_BLOCKS, Material.getMaterial(58), 20, 10),
	FURNACE(KindItem.BUILDING_BLOCKS, Material.FURNACE, 20, 10),
	LADDER(KindItem.BUILDING_BLOCKS, Material.LADDER, 20, 10),
	SNOW_LAYER(KindItem.BUILDING_BLOCKS, Material.SNOW, 20, 10),
	CACTUS(KindItem.BUILDING_BLOCKS, Material.CACTUS, 40, 20),
	JUKEBOX(KindItem.BUILDING_BLOCKS, Material.JUKEBOX, 360, 180),
	FENCE(KindItem.BUILDING_BLOCKS, Material.FENCE, 30, 15),
	IRON_BARDING(KindItem.BUILDING_BLOCKS, Material.IRON_BARDING, 720, 360),
	GLASS_PANE(KindItem.BUILDING_BLOCKS, Material.getMaterial(102), 25, 10),
	VINE(KindItem.BUILDING_BLOCKS, Material.VINE, 30, 15),
	WATER_LILY(KindItem.BUILDING_BLOCKS, Material.WATER_LILY, 30, 15),
	NETHER_BRICK_FENCE(KindItem.BUILDING_BLOCKS, Material.NETHER_FENCE, 30, 15),
	ENCHANTING_TABLE(KindItem.BUILDING_BLOCKS, Material.ENCHANTMENT_TABLE, 496, 248),
	ENDER_CHEST(KindItem.BUILDING_BLOCKS, Material.ENDER_CHEST, 512, 256),
	COBBLESTONE_WALL(KindItem.BUILDING_BLOCKS, Material.COBBLE_WALL, 30, 15),
	MOSSY_COBBLESTONE_WALL(KindItem.BUILDING_BLOCKS, Material.COBBLE_WALL, 1, 30, 15),
	WHITE_GLASS_PANE(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS_PANE, 25, 10),
	ORANGE_GLASS_PANE(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS_PANE, 1, 25, 10),
	MAGENTA_GLASS_PANE(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS_PANE, 2, 25, 10),
	LIGHT_BLUE_GLASS_PANE(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS_PANE, 3, 25, 10),
	YELLOW_GLASS_PANE(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS_PANE, 4, 25, 10),
	LIME_GLASS_PANE(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS_PANE, 5, 25, 10),
	PINK_GLASS_PANE(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS_PANE, 6, 25, 10),
	GRAY_GLASS_PANE(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS_PANE, 7, 25, 10),
	LIGHT_GLASS_PANE(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS_PANE, 8, 25, 10),
	CYAN_GLASS_PANE(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS_PANE, 9, 25, 10),
	PURPLE_GLASS_PANE(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS_PANE, 10, 25, 10),
	BLUE_GLASS_PANE(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS_PANE, 11, 25, 10),
	BROWN_GLASS_PANE(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS_PANE, 12, 25, 10),
	GREEN_GLASS_PANE(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS_PANE, 13, 25, 10),
	RED_GLASS_PANE(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS_PANE, 14, 25, 10),
	BLACK_GLASS_PANE(KindItem.BUILDING_BLOCKS, Material.STAINED_GLASS_PANE, 15, 25, 10),
	SLIME(KindItem.BUILDING_BLOCKS, Material.SLIME_BLOCK, 1, 500, 10),
	WHITE_CARPET(KindItem.BUILDING_BLOCKS, Material.CARPET, 25, 10),
	ORANGE_CARPET(KindItem.BUILDING_BLOCKS, Material.CARPET, 1, 25, 10),
	MAGENTA_CARPET(KindItem.BUILDING_BLOCKS, Material.CARPET, 2, 25, 10),
	LIGHT_BLUE_CARPET(KindItem.BUILDING_BLOCKS, Material.CARPET, 3, 25, 10),
	YELLOW_CARPET(KindItem.BUILDING_BLOCKS, Material.CARPET, 4, 25, 10),
	LIME_CARPET(KindItem.BUILDING_BLOCKS, Material.CARPET, 5, 25, 10),
	PINK_CARPET(KindItem.BUILDING_BLOCKS, Material.CARPET, 6, 25, 10),
	GRAY_CARPET(KindItem.BUILDING_BLOCKS, Material.CARPET, 7, 25, 10),
	LIGHT_GRAY_CARPET(KindItem.BUILDING_BLOCKS, Material.CARPET, 8, 25, 10),
	CYAN_CARPET(KindItem.BUILDING_BLOCKS, Material.CARPET, 9, 25, 10),
	PURPLE_CARPET(KindItem.BUILDING_BLOCKS, Material.CARPET, 10, 25, 10),
	BLUE_CARPET(KindItem.BUILDING_BLOCKS, Material.CARPET, 11, 25, 10),
	BROWN_CARPET(KindItem.BUILDING_BLOCKS, Material.CARPET, 12, 25, 10),
	GREEN_CARPET(KindItem.BUILDING_BLOCKS, Material.CARPET, 13, 25, 10),
	RED_CARPET(KindItem.BUILDING_BLOCKS, Material.CARPET, 14, 25, 10),
	BLACK_CARPET(KindItem.BUILDING_BLOCKS, Material.CARPET, 15, 25, 10),
	SPRUCE_FENCE(KindItem.BUILDING_BLOCKS, Material.SPRUCE_FENCE, 30, 15),
	BIRCH_FENCE(KindItem.BUILDING_BLOCKS, Material.BIRCH_FENCE, 30, 15),
	JUNGLE_FENCE(KindItem.BUILDING_BLOCKS, Material.JUNGLE_FENCE, 30, 15),
	DARK_FENCE(KindItem.BUILDING_BLOCKS, Material.DARK_OAK_FENCE, 30, 15),
	ACACIA_FENCE(KindItem.BUILDING_BLOCKS, Material.ACACIA_FENCE, 30, 15),
	END_ROD(KindItem.BUILDING_BLOCKS, Material.END_ROD, 50, 25),
	CHORUS_PLANT(KindItem.BUILDING_BLOCKS, Material.CHORUS_PLANT, 100, 50),
	CHORUS_FLOWER(KindItem.BUILDING_BLOCKS, Material.CHORUS_FLOWER, 100, 50),
	WHITE_SHULKER(KindItem.BUILDING_BLOCKS, Material.WHITE_SHULKER_BOX, 80, 40),
	ORANGE_SHULKER(KindItem.BUILDING_BLOCKS, Material.ORANGE_SHULKER_BOX, 80, 40),
	MAGENTA_SHULKER(KindItem.BUILDING_BLOCKS, Material.MAGENTA_SHULKER_BOX, 80, 40),
	LIGHT_BLUE_SHULKER(KindItem.BUILDING_BLOCKS, Material.LIGHT_BLUE_SHULKER_BOX, 80, 40),
	YELLOW_SHULKER(KindItem.BUILDING_BLOCKS, Material.YELLOW_SHULKER_BOX, 80, 40),
	LIME_SHULKER(KindItem.BUILDING_BLOCKS, Material.LIME_SHULKER_BOX, 80, 40),
	PINK_SHULKER(KindItem.BUILDING_BLOCKS, Material.PINK_SHULKER_BOX, 80, 40),
	GRAY_SHULKER(KindItem.BUILDING_BLOCKS, Material.GRAY_SHULKER_BOX, 80, 40),
	LIGHT_GRAY_SHULKER(KindItem.BUILDING_BLOCKS, Material.SILVER_SHULKER_BOX, 80, 40),
	CYAN_SHULKER(KindItem.BUILDING_BLOCKS, Material.CYAN_SHULKER_BOX, 80, 40),
	PURPLE_SHULKER(KindItem.BUILDING_BLOCKS, Material.PURPLE_SHULKER_BOX, 80, 40),
	BLUE_SHULKER(KindItem.BUILDING_BLOCKS, Material.BLUE_SHULKER_BOX, 80, 40),
	BROWN_SHULKER(KindItem.BUILDING_BLOCKS, Material.BROWN_SHULKER_BOX, 80, 40),
	GREEN_SHULKER(KindItem.BUILDING_BLOCKS, Material.GREEN_SHULKER_BOX, 80, 40),
	RED_SHULKER(KindItem.BUILDING_BLOCKS, Material.RED_SHULKER_BOX, 80, 40),
	BLACK_SHULKER(KindItem.BUILDING_BLOCKS, Material.BLACK_SHULKER_BOX, 80, 40),
	WHITE_GLAZED_TERRACOTTA(KindItem.BUILDING_BLOCKS, Material.WHITE_GLAZED_TERRACOTTA, 80, 40),
	ORANGE_GLAZED_TERRACOTTA(KindItem.BUILDING_BLOCKS, Material.ORANGE_GLAZED_TERRACOTTA, 80, 40),
	MAGENTA_GLAZED_TERRACOTTA(KindItem.BUILDING_BLOCKS, Material.MAGENTA_GLAZED_TERRACOTTA, 80, 40),
	LIGHT_BLUE_GLAZED_TERRACOTTA(KindItem.BUILDING_BLOCKS, Material.LIGHT_BLUE_GLAZED_TERRACOTTA, 80, 40),
	YELLOW_GLAZED_TERRACOTTA(KindItem.BUILDING_BLOCKS, Material.YELLOW_GLAZED_TERRACOTTA, 80, 40),
	LIME_GLAZED_TERRACOTTA(KindItem.BUILDING_BLOCKS, Material.LIME_GLAZED_TERRACOTTA, 80, 40),
	PINK_GLAZED_TERRACOTTA(KindItem.BUILDING_BLOCKS, Material.PINK_GLAZED_TERRACOTTA, 80, 40),
	GRAY_GLAZED_TERRACOTTA(KindItem.BUILDING_BLOCKS, Material.GRAY_GLAZED_TERRACOTTA, 80, 40),
	LIGHT_GRAY_GLAZED_TERRACOTTA(KindItem.BUILDING_BLOCKS, Material.SILVER_GLAZED_TERRACOTTA, 80, 40),
	CYAN_GLAZED_TERRACOTTA(KindItem.BUILDING_BLOCKS, Material.CYAN_GLAZED_TERRACOTTA, 80, 40),
	PURPLE_GLAZED_TERRACOTTA(KindItem.BUILDING_BLOCKS, Material.PURPLE_GLAZED_TERRACOTTA, 80, 40),
	BLUE_GLAZED_TERRACOTTA(KindItem.BUILDING_BLOCKS, Material.BLUE_GLAZED_TERRACOTTA, 80, 40),
	BROWN_GLAZED_TERRACOTTA(KindItem.BUILDING_BLOCKS, Material.BROWN_GLAZED_TERRACOTTA, 80, 40),
	GREEN_GLAZED_TERRACOTTA(KindItem.BUILDING_BLOCKS, Material.GREEN_GLAZED_TERRACOTTA, 80, 40),
	RED_GLAZED_TERRACOTTA(KindItem.BUILDING_BLOCKS, Material.RED_GLAZED_TERRACOTTA, 80, 40),
	BLACK_GLAZED_TERRACOTTA(KindItem.BUILDING_BLOCKS, Material.BLACK_GLAZED_TERRACOTTA, 80, 40),
	
	/*
	 * > Type: Food items
	 */
	APPLE(KindItem.FOODSTUFFS, Material.APPLE, 50, 25),
	MUSHROOM_SOUP(KindItem.FOODSTUFFS, Material.MUSHROOM_SOUP, 40, 20),
	BREAD(KindItem.FOODSTUFFS, Material.BREAD, 40, 20),
	RAW_BEEF(KindItem.FOODSTUFFS, Material.RAW_BEEF, 5, 1),
	COOKED_BEEF(KindItem.FOODSTUFFS, Material.COOKED_BEEF, 25, 10),
	GOLDEN_APPLE(KindItem.FOODSTUFFS, Material.GOLDEN_APPLE, 1280, 640),
	BLOCK_APPLE(KindItem.FOODSTUFFS, Material.GOLDEN_APPLE, 1, 3500, 1250),
	RAW_FISH(KindItem.FOODSTUFFS, Material.RAW_FISH, 5, 1),
	RAW_SALMON(KindItem.FOODSTUFFS, Material.RAW_FISH, 1, 20, 10),
	CLOWN_FISH(KindItem.FOODSTUFFS, Material.RAW_FISH, 2, 20, 10),
	PUFFER_FISH(KindItem.FOODSTUFFS, Material.RAW_FISH, 3 , 20, 10),
	COOKED_FISH(KindItem.FOODSTUFFS, Material.COOKED_FISH, 25, 10),
	COOKED_SALMON(KindItem.FOODSTUFFS, Material.COOKED_FISH, 1, 25, 10),
	CAKE(KindItem.FOODSTUFFS, Material.CAKE, 20, 10),
	COOKIE(KindItem.FOODSTUFFS, Material.COOKIE, 10, 5),
	MELON(KindItem.FOODSTUFFS, Material.MELON, 100, 50),
	RAW_CHICKEN(KindItem.FOODSTUFFS, Material.RAW_CHICKEN, 5, 1),
	COOKED_CHICKEN(KindItem.FOODSTUFFS, Material.COOKED_CHICKEN, 15, 5),
	ROTTEN_FLESH(KindItem.FOODSTUFFS, Material.ROTTEN_FLESH, 5, 1),
	SPIDER_EYE(KindItem.FOODSTUFFS, Material.SPIDER_EYE, 5, 1),
	BAKED_POTATO(KindItem.FOODSTUFFS, Material.BAKED_POTATO, 10, 5),
	POISONOUS_POTATO(KindItem.FOODSTUFFS, Material.POISONOUS_POTATO, 5, 1),
	PUMPKIN_PIE(KindItem.FOODSTUFFS, Material.PUMPKIN_PIE, 25, 10),
	RABBIT(KindItem.FOODSTUFFS, Material.RABBIT, 5, 1),
	COOKED_RABBIT(KindItem.FOODSTUFFS, Material.COOKED_RABBIT, 25, 10),
	RABBIT_STEW(KindItem.FOODSTUFFS, Material.RABBIT_STEW, 25, 10),
	MUTTON(KindItem.FOODSTUFFS, Material.MUTTON, 5, 1),
	COOKED_MUTTON(KindItem.FOODSTUFFS, Material.COOKED_MUTTON, 15, 5),
	BEETROOT(KindItem.FOODSTUFFS, Material.BEETROOT, 10, 5),
	BEETROOT_SOUP(KindItem.FOODSTUFFS, Material.BEETROOT_SOUP, 20, 10),
	CARROT(KindItem.FOODSTUFFS, Material.CARROT, 20, 10),
	POTATO(KindItem.FOODSTUFFS, Material.POTATO, 20, 10),
	
	/*
	 * > Type: Armors items
	 */
	
	LEATHER_HELMET(KindItem.ARMORS, Material.LEATHER_HELMET, 50, 25),
	LEATHER_CHESTPLATE(KindItem.ARMORS, Material.LEATHER_CHESTPLATE, 80, 40),
	LEATHER_LEGGINGS(KindItem.ARMORS, Material.LEATHER_LEGGINGS, 70, 35),
	LEATHER_BOOTS(KindItem.ARMORS, Material.LEATHER_BOOTS, 40, 20),
	WOOD_SWORD(KindItem.ARMORS, Material.WOOD_SWORD, 15, 5),
	BOW(KindItem.ARMORS, Material.BOW, 15, 5),
	ARROW(KindItem.ARMORS, Material.ARROW, 25, 10),
	CHAINMAIL_HELMET(KindItem.ARMORS, Material.CHAINMAIL_HELMET, 100, 50),
	CHAINMAIL_CHESTPLATE(KindItem.ARMORS, Material.CHAINMAIL_CHESTPLATE, 160, 80),
	CHAINMAIL_LEGGINGS(KindItem.ARMORS, Material.CHAINMAIL_LEGGINGS, 140, 70),
	CHAINMAIL_BOOTS(KindItem.ARMORS, Material.CHAINMAIL_BOOTS, 80, 40),
	STONE_SWORD(KindItem.ARMORS, Material.STONE_SWORD, 15, 5),
	IRON_HELMET(KindItem.ARMORS, Material.IRON_HELMET, 140, 350),
	IRON_CHESTPLATE(KindItem.ARMORS, Material.IRON_CHESTPLATE, 140, 54),
	IRON_LEGGINGS(KindItem.ARMORS, Material.IRON_LEGGINGS, 980, 490),
	IRON_BOOTS(KindItem.ARMORS, Material.IRON_BOOTS, 560, 280),
	IRON_SWORD(KindItem.ARMORS, Material.IRON_SWORD, 280, 140),
	SHIELD(KindItem.ARMORS, Material.SHIELD, 170, 85),
	GOLD_HELMET(KindItem.ARMORS, Material.GOLD_HELMET, 500, 250),
	GOLD_CHESTPLATE(KindItem.ARMORS, Material.GOLD_CHESTPLATE, 900, 450),
	GOLD_LEGGINGS(KindItem.ARMORS, Material.GOLD_LEGGINGS, 700, 350),
	GOLD_BOOTS(KindItem.ARMORS, Material.GOLD_BOOTS, 400, 200),
	GOLD_SWORD(KindItem.ARMORS, Material.GOLD_SWORD, 300, 150),
	DIAMOND_HELMET(KindItem.ARMORS, Material.DIAMOND_HELMET, 1000, 500),
	DIAMOND_CHESTPLATE(KindItem.ARMORS, Material.DIAMOND_CHESTPLATE, 1500, 750),
	DIAMOND_LEGGINGS(KindItem.ARMORS, Material.DIAMOND_LEGGINGS, 1200, 600),
	DIAMOND_BOOTS(KindItem.ARMORS, Material.DIAMOND_BOOTS, 900, 450),
	DIAMOND_SWORD(KindItem.ARMORS, Material.DIAMOND_SWORD, 400, 200),
	
	/*
	 * > Type: Tools items
	 */
	IRON_SPADE(KindItem.TOOLS, Material.IRON_SPADE, 60,30),
	IRON_PICKAXE(KindItem.TOOLS, Material.IRON_PICKAXE, 100, 50),
	IRON_AXE(KindItem.TOOLS, Material.IRON_AXE, 450, 40),
	FLINT_AND_STEEL(KindItem.TOOLS, Material.FLINT_AND_STEEL, 100, 25),
	WOOD_SPADE(KindItem.TOOLS, Material.WOOD_SPADE, 100, 5),
	WOOD_PICKAXE(KindItem.TOOLS, Material.WOOD_PICKAXE, 100, 5),
	WOOD_AXE(KindItem.TOOLS, Material.WOOD_AXE, 100, 5),
	STONE_SPADE(KindItem.TOOLS, Material.STONE_SPADE, 200, 15),
	STONE_PICKAXE(KindItem.TOOLS, Material.STONE_PICKAXE, 200, 40),
	STONE_AXE(KindItem.TOOLS, Material.STONE_AXE, 200, 20),
	DIAMOND_SPADE(KindItem.TOOLS, Material.DIAMOND_SPADE, 600, 300),
	DIAMOND_PICKAXE(KindItem.TOOLS, Material.DIAMOND_PICKAXE, 600, 350),
	DIAMOND_AXE(KindItem.TOOLS, Material.DIAMOND_AXE, 100, 50),
	GOLD_SPADE(KindItem.TOOLS, Material.GOLD_SPADE, 200, 25),
	GOLD_PICKAXE(KindItem.TOOLS, Material.GOLD_PICKAXE, 200, 35),
	GOLD_AXE(KindItem.TOOLS, Material.GOLD_AXE, 200, 30),
	WOOD_HOE(KindItem.TOOLS, Material.WOOD_HOE, 100, 5),
	STONE_HOE(KindItem.TOOLS, Material.STONE_HOE, 100, 7),
	IRON_HOE(KindItem.TOOLS, Material.IRON_HOE, 100, 10),
	DIAMOND_HOE(KindItem.TOOLS, Material.DIAMOND_HOE, 560, 12),
	GOLD_HOE(KindItem.TOOLS, Material.GOLD_HOE, 120, 8),
	COMPASS(KindItem.TOOLS, Material.COMPASS, 120, 50),
	FISHING_ROD(KindItem.TOOLS, Material.FISHING_ROD, 102, 40),
	WATCH(KindItem.TOOLS, Material.WATCH, 200, 25),
	SHEARS(KindItem.TOOLS, Material.SHEARS, 200, 30),
	LEASH(KindItem.TOOLS, Material.LEASH, 100, 40),
	NAME_TAG(KindItem.TOOLS, Material.NAME_TAG, 1000, 40),

	
	; 
	
	public KindItem getKind() {
		return kind;
	}

	public void setKind(KindItem kind) {
		this.kind = kind;
	}

	private Material material;
	private int data;
	private int priceBuy;
	private int priceSell;
	
	private KindItem kind;
	

	AdminShopItem(KindItem kind, Material material, int priceBuy, int priceSell){
		
		this.kind = kind;
		
		this.material = material;
		this.data = 0;
		this.priceBuy = priceBuy;
		this.priceSell = priceSell;
		
	}
	
	AdminShopItem(KindItem kind, Material material, int data, int priceBuy, int priceSell){
		
		this.kind = kind;
		
		this.material = material;
		this.data = data;
		this.priceBuy = priceBuy;
		this.priceSell = priceSell;

		
	}
	
	public int getData() {
		return data;
	}

	public void setData(int data) {
		this.data = data;
	}

	public int getPriceBuy() {
		return priceBuy;
	}

	public void setPriceBuy(int priceBuy) {
		this.priceBuy = priceBuy;
	}

	public int getPriceSell() {
		return priceSell;
	}

	public void setPriceSell(int priceSell) {
		this.priceSell = priceSell;
	}

	public Material getMaterial() {
		return material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}
	
	public static int getBuyPriceByMaterial (Material materia){
			for(AdminShopItem asi : AdminShopItem.values()){
				if(asi.getMaterial().equals(materia)){
					return asi.getPriceBuy();
				}
			}
			return 0;
	}
	
	public static int getSellPriceByMaterial (Material materia){
		for(AdminShopItem asi : AdminShopItem.values()){
			if(asi.getMaterial().equals(materia)){
				return asi.getPriceSell();
			}
		}
		return 0;
}
}
