package net.omniblock.shop.utils;

import java.util.HashMap;
import java.util.Map;

import org.apache.commons.lang.WordUtils;
import org.bukkit.Material;

public enum ItemNameUtils {
   
	UNKNOW("item"),
    ACACIA_DOOR("acacia door"),
    ACACIA_DOOR_ITEM("acacia door"),
    ACACIA_FENCE("acacia fence"),
    ACACIA_FENCE_GATE("acacia fence gate"),
    ACACIA_STAIRS("acacia wood stairs"),
    ACTIVATOR_RAIL("activator rail"),
    AIR("air"),
    ANVIL("anvil"),
    APPLE("apple"),
    ARMOR_STAND("armor stand"),
    ARROW("arrow"),
    BAKED_POTATO("baked potato"),
    BANNER("banner"),
    BARRIER("barrier"),
    BEACON("beacon"),
    BED("bed"),
    BED_BLOCK("bed block"),
    BEDROCK("bedrock"),
    BIRCH_DOOR("birch door"),
    BIRCH_DOOR_ITEM("birch door"),
    BIRCH_FENCE("birch fence"),
    BIRCH_FENCE_GATE("birch fence gate"),
    BIRCH_WOOD_STAIRS("birch wood stairs"),
    BLAZE_POWDER("blaze powder"),
    BLAZE_ROD("blaze rod"),
    BOAT("boat"),
    BONE("bone"),
    BOOK("book"),
    BOOK_AND_QUILL("book and quill"),
    BOOKSHELF("bookshelf"),
    BOW("bow"),
    BOWL("bowl"),
    BREAD("bread"),
    BREWING_STAND("brewing stand"),
    BREWING_STAND_ITEM("brewing stand"),
    BRICK("bricks"),
    BRICK_STAIRS("brick stairs"),
    BROWN_MUSHROOM("brown mushroom"),
    BUCKET("bucket"),
    BURNING_FURNACE("furnace"),
    CACTUS("cactus"),
    CAKE("cake"),
    CAKE_BLOCK("cake"),
    CARPET("carpet"),
    CARROT("carrot"),
    CARROT_ITEM("carrot"),
    CARROT_STICK("carrot on a stick"),
    CAULDRON("cauldron"),
    CAULDRON_ITEM("cauldron"),
    CHAINMAIL_BOOTS("chainmail boots"),
    CHAINMAIL_CHESTPLATE("chainmail chestplate"),
    CHAINMAIL_HELMET("chainmail helmet"),
    CHAINMAIL_LEGGINGS("chainmail leggings"),
    CHEST("chest"),
    CLAY("clay"),
    CLAY_BALL("clay"),
    CLAY_BRICK("brick"),
    COAL("coal"),
    COAL_BLOCK("block of coal"),
    COAL_ORE("coal ore"),
    COBBLE_WALL("cobblestone wall"),
    COBBLESTONE("cobblestone"),
    COBBLESTONE_STAIRS("cobblestone stairs"),
    COCOA("cocoa"),
    COMMAND("command block"),
    COMPASS("compass"),
    COOKED_BEEF("steak"),
    COOKED_CHICKEN("cooked chicken"),
    COOKED_FISH("cooked fish"),
    COOKIE("cookie"),
    CROPS("crops"),
    DARK_OAK_DOOR("dark oak door"),
    DARK_OAK_DOOR_ITEM("dark oak door"),
    DARK_OAK_FENCE("dark oak fence"),
    DARK_OAK_FENCE_GATE("dark oak fence gate"),
    DARK_OAK_STAIRS("dark oak wood stairs"),
    DAYLIGHT_DETECTOR("daylight sensor"),
    DEAD_BUSH("dead bush"),
    DETECTOR_RAIL("detector rail"),
    DIAMOND("diamond"),
    DIAMOND_AXE("diamond axe"),
    DIAMOND_BARDING("diamond horse armor"),
    DIAMOND_BLOCK("diamond block"),
    DIAMOND_BOOTS("diamond boots"),
    DIAMOND_CHESTPLATE("diamond chestplate"),
    DIAMOND_HELMET("diamond helmet"),
    DIAMOND_HOE("diamond hoe"),
    DIAMOND_LEGGINGS("diamond leggings"),
    DIAMOND_ORE("diamond ore"),
    DIAMOND_PICKAXE("diamond pickaxe"),
    DIAMOND_SPADE("diamond shovel"),
    DIAMOND_SWORD("diamond sword"),
    DIODE("redstone repeater"),
    DIODE_BLOCK_OFF("redstone repeater"),
    DIODE_BLOCK_ON("redstone repeater"),
    DIRT("dirt"),
    DISPENSER("dispenser"),
    DOULBE_PLANT("double plant"),
    DOUBLE_STEP("double slab"),
    DOUBLE_STONE_SLAB2("double slab"),
    DRAGON_EGG("dragon egg"),
    DROPPER("dropper"),
    EGG("egg"),
    EMERALD("emerald"),
    EMERALD_BLOCK("emerald block"),
    EMERALD_ORE("emerald ore"),
    EMPTY_MAP("empty map"),
    ENCHANTED_BOOK("enchanted book"),
    ENCHANTMENT_TABLE("enchantment table"),
    ENDER_CHEST("ender chest"),
    ENDER_PEARL("ender pearl"),
    ENDER_PORTAL("ender portal"),
    ENDER_PORTAL_FRAME("ender protal frame"),
    ENDER_STONE("ender stone"),
    EXP_BOTTLE("bottle o' enchanting"),
    EXPLOSIVE_MINECART("minecart with tnt"),
    EYE_OF_ENDER("eye of ender"),
    FEATHER("feather"),
    FENCE("fence"),
    FENCE_GATE("fence gate"),
    FERMENTED_SPIDER_EYE("fermented spider eye"),
    FIRE("fire"),
    FIREBALL("fireball"),
    FIREWORK("firework"),
    FIREWORK_CHARGE("firework charge"),
    FISHING_ROD("fishing rod"),
    FLINT("flint"),
    FLINT_AND_STEEL("flint and steel"),
    FLOWER_POT("flower pot"),
    FLOWER_POT_ITEM("flower pot"),
    FURNACE("furnace"),
    GHAST_TEAR("ghast tear"),
    GLASS("glass"),
    GLASS_BOTTLE("glass bottle"),
    GLOWING_REDSTONE_ORE("redstone ore"),
    GLOWSTONE("glowstone"),
    GLOWSTONE_DUST("glowstone dust"),
    GOLD_AXE("gold axe"),
    GOLD_BARDING("gold horse armor"),
    GOLD_BLOCK("gold block"),
    GOLD_BOOTS("gold boots"),
    GOLD_CHESTPLATE("gold chestplate"),
    GOLD_HELMET("gold helmet"),
    GOLD_HOE("gold hoe"),
    GOLD_INGOT("gold ingot"),
    GOLD_LEGGINGS("gold leggings"),
    GOLD_NUGGET("gold nugget"),
    GOLD_ORE("gold ore"),
    GOLD_PICKAXE("gold pickaxe"),
    GOLD_PLATE("weighted pressure plate"),
    GOLD_RECORD("music disc - 13"),
    GOLD_SPADE("gold shovel"),
    GOLD_SWORD("gold sword"),
    GOLDEN_APPLE("golden apple"),
    GOLDEN_CARROT("golden carrot"),
    GRASS("grass"),
    GRAVEL("gravel"),
    GREEN_RECORD("music disc - cat"),
    GRILLED_PORK("cooked porkchop"),
    HARD_CLAY("hardened clay"),
    HAY_BLOCK("hay bale"),
    HOPPER("hopper"),
    HOPPER_MINECART("minecart with hopper"),
    HUGE_MUSHROOM_1("huge mushroom"),
    HUGE_MUSHROOM_2("huge mushroom"),
    ICE("ice"),
    INK_SACK("ink sack"),
    IRON_AXE("iron axe"),
    IRON_BARDING("iron horse armor"),
    IRON_BLOCK("iron block"),
    IRON_BOOTS("iron boots"),
    IRON_CHESTPLATE("iron chestplate"),
    IRON_DOOR("iron door"),
    IRON_DOOR_BLOCK("iron door block"),
    IRON_FENCE("iron fence"),
    IRON_HELMET("iron helmet"),
    IRON_HOE("iron hoe"),
    IRON_INGOT("iron ingot"),
    IRON_LEGGINGS("iron leggings"),
    IRON_ORE("iron ore"),
    IRON_PICKAXE("iron pickaxe"),
    IRON_PLATE("weighted pressure plate"),
    IRON_SPADE("iron shovel"),
    IRON_SWORD("iron sword"),
    ITEM_FRAME("item frame"),
    JACK_O_LANTERN("jack-o-lantern"),
    JUKEBOX("jukebox"),
    JUNGLE_DOOR("jungle door"),
    JUNGLE_DOOR_ITEM("jungle door"),
    JUNGLE_FENCE("jungle fence"),
    JUNGLE_FENCE_GATE("jungle fence gate"),
    JUNGLE_WOOD_STAIRS("jungle wood stairs"),
    LADDER("ladder"),
    LAPIS_BLOCK("lapis lazuli block"),
    LAPIS_ORE("lapis lazuli ore"),
    LAVA("lava"),
    LAVA_BUCKET("lava bucket"),
    LEASH("lead"),
    LEATHER("leather"),
    LEATHER_BOOTS("leather boots"),
    LEATHER_CHESTPLATE("leather tunic"),
    LEATHER_HELMET("leather cap"),
    LEATHER_LEGGINGS("leather pants"),
    LEAVES("leaves"),
    LEAVES_2("leaves"),
    LEVER("lever"),
    LOG("wood log"),
    LOG_2("wood log"),
    LONG_GRASS("shrub"),
    MAGMA_CREAM("magma cream"),
    MAP("map"),
    MELON("melon"),
    MELON_BLOCK("melon"),
    MELON_SEEDS("melon seeds"),
    MELON_STEM("melon stem"),
    MILK_BUCKET("milk bucket"),
    MINECART("minecart"),
    MOB_SPAWNER("mob spawner"),
    MONSTER_EGG("mob egg"),
    MONSTER_EGGS("silverfish block"),
    MOSSY_COBBLESTONE("mossy cobblestone"),
    MUSHROOM_SOUP("mushroom soup"),
    MYCEL("mycelium"),
    NAME_TAG("name tag"),
    NETHER_BRICK("nether brick"),
    NETHER_BRICK_ITEM("nether brick"),
    NETHER_BRICK_STAIRS("nether brick stairs"),
    NETHER_FENCE("nether brick fence"),
    NETHER_STALK("nether wart"),
    NETHER_STAR("nether star"),
    NETHER_WARTS("nether wart"),
    NETHERRACK("netherrack"),
    NOTE_BLOCK("note block"),
    OBSIDIAN("obsidian"),
    PAINTING("painting"),
    PAPER("paper"),
    PISTON_BASE("piston"),
    PISTON_EXTENSION("piston extension"),
    PISTON_MOVING_PIECE("moving piston"),
    PISTON_STICK_BASE("sticky piston"),
    POISONOUS_POTATO("poisonous potato"),
    PORK("raw porkchop"),
    PORTAL("portal"),
    POTATO("potato"),
    POTATO_ITEM("potato"),
    POTION("potion"),
    POWERED_MINECART("minecart with furnace"),
    POWERED_RAIL("powered rail"),
    PRISMARINE("prismarine"),
    PRISMARINE_CRYSTALS("prismarine crystals"),
    PRISMARINE_SHARD("prismarine shard"),
    PUMPKIN("pumpkin"),
    PUMPKIN_PIE("pumpkin pie"),
    PUMPKIN_SEEDS("pumpkin seeds"),
    PUMPKIN_STEM("calabaza"),
    QUARTZ("cuarzo"),
    QUARTZ_BLOCK("bloque de cuarzo"),
    QUARTZ_ORE("mena de cuarzo"),
    QUARTZ_STAIRS("escaleras"),
    RABBIT("conejo"),
    RABBIT_FOOT("pie de conejo"),
    RABBIT_HIDE("piel de conejo"),
    RABBIT_STEW("estofado"),
    RAILS("raíl"),
    RAW_BEEF("filete crudo"),
    RAW_CHICKEN("pollo crudo"),
    RAW_FISH("pescado crudo"),
    RECORD_10("disco - ward"),
    RECORD_11("disco - 11"),
    RECORD_12("disco - wait"),
    RECORD_3("disco - blocks"),
    RECORD_4("disco - chirp"),
    RECORD_5("disco - far"),
    RECORD_6("disco - mall"),
    RECORD_7("disco - mellohi"),
    RECORD_8("disco - stal"),
    RECORD_9("disco - strad"),
    RED_MUSHROOM("champiñón"),
    RED_ROSE("rosa roja"),
    RED_SANDSTONE("arenisca roja"),
    RED_SANDSTONE_STAIRS("escaleras"),
    REDSTONE("redstone"),
    REDSTONE_BLOCK("bloque de redstone"),
    REDSTONE_COMPARATOR("comparador"),
    REDSTONE_COMPARATOR_OFF("compradador"),
    REDSTONE_COMPARATOR_ON("comparador"),
    REDSTONE_LAMP_OFF("lámpara"),
    REDSTONE_LAMP_ON("lámpara"),
    REDSTONE_ORE("mena de redstone"),
    REDSTONE_TORCH_OFF("antorcha de redstone"),
    REDSTONE_TORCH_ON("antorcha de redstone"),
    REDSTONE_WIRE("redstone"),
    ROTTEN_FLESH("carne de zombie"),
    SADDLE("montura"),
    SAND("arena"),
    SANDSTONE("arenisca"),
    SANDSTONE_STAIRS("escaleras"),
    SAPLING("brote de árbol"),
    SEA_LANTERN("linterna de agua"),
    SEEDS("semillas"),
    SHEARS("tijeras"),
    SIGN("cartel"),
    SIGN_POST("cartel"),
    SKULL("cabeza"),
    SKULL_ITEM("cabeza"),
    SLIME_BLOCK("bloque de slime"),
    SMOOTH_BRICK("ladrillos"),
    SMOOTH_STAIRS("escaleras"),
    SNOW("nieve"),
    SNOW_BALL("bolas de nieve"),
    SNOW_BLOCK("bloque de nieve"),
    SOIL("tierra arada"),
    SOUL_SAND("arena de almas"),
    SPECKLED_MELON("sandía reluciente"),
    SPIDER_EYE("ojo de araña"),
    SPONGE("esponja"),
    SPRUCE_DOOR("puerta"),
    SPRUCE_DOOR_ITEM("puerta"),
    SPRUCE_FENCE("valla"),
    SPRUCE_FENCE_GATE("valla"),
    SPRUCE_WOOD_STAIRS("escaleras"),
    STAINED_CLAY("arcilla tintada"),
    STAINED_GLASS("cristal tintado"),
    STAINED_GLASS_PANE("panel tintado"),
    STANDING_BANNER("estandarte"),
    STATIONARY_LAVA("lava estática"),
    STEP("losa"),
    STICK("palo"),
    STONE("piedra"),
    STONE_AXE("hacha de piedra"),
    STONE_BUTTON("botón"),
    STONE_HOE("azada de piedra"),
    STONE_PICKAXE("pico de piedra"),
    STONE_PLATE("placa de presión"),
    STONE_SLAB2("losa de piedra"),
    STONE_SPADE("pala de piedra"),
    STONE_SWORD("espada de piedra"),
    STORAGE_MINECART("minecart"),
    STRING("hilo"),
    SUGAR("azucar"),
    SUGAR_CANE("caña de azucar"),
    SUGAR_CANE_BLOCK("caña de azucar"),
    SULPHUR("pólvora"),
    THIN_GLASS("panel de cristal"),
    TNT("tnt"),
    TORCH("antorcha"),
    TRAP_DOOR("trampilla"),
    TRAPPED_CHEST("cofre trampa"),
    TRIPWIRE("gancho"),
    TRIPWIRE_HOOK("gancho"),
    VINE("enredadera"),
    WALL_BANNER("estandarte"),
    WALL_SIGN("cartel"),
    WATCH("reloj"),
    WATER("agua"),
    WATER_BUCKET("cubo de agua"),
    WATER_LILY("nenúfar"),
    WEB("telaraña"),
    WHEAT("trigo"),
    WOOD("madera"),
    WOOD_AXE("hacha de madera"),
    WOOD_BUTTON("botón"),
    WOOD_DOOR("puerta de madera"),
    WOOD_DOUBLE_STEP("doble losa"),
    WOOD_HOE("azada de madera"),
    WOOD_PICKAXE("pico de madera"),
    WOOD_PLATE("placa de presión"),
    WOOD_SPADE("pala de madera"),
    WOOD_STAIRS("escaleras"),
    WOOD_STEP("losa de madera"),
    WOOD_SWORD("espada de amdera"),
    WOODEN_DOOR("puerta de madera"),
    WOOL("lana"),
    WORKBENCH("mesa de crafteo"),
    WRITTEN_BOOK("libro escrito"),
    YELLOW_FLOWER("diente de león"),
    END_BRICKS("ladrillos"),
    PURPUR_BLOCK("púrpur"),
    PURPUR_PILLAR("pilar"),
    PUPUR_STAIRS("escaleras"),
    PURPUR_SLAB("losa"),
    KNOWLEDGE_BOOK("gran libro"),
    IRON_NUGGET("pepita de hierro"),
    SHULKER_SHELL("caparazón"),
    TOTEM("tótem"),
    BOAT_DARK_OAK("barca"),
    BOAT_ACACIA("barca"),
    BOAT_JUNGLE("barca"),
    BOAT_BIRCH("barca"),
    BOAT_SPRUCE("barca"),
    ELYTRA("élitros"),
    SHIELD("escudo"),
    LINGERING_POTION("poción persistente"),
    TIPPED_ARROW("flecha quimica"),
    SPECTRAL_ARROW("flecha espectral"),
    SPLASH_POTION("poción splash"),
    DRAGONS_BREATH("aliento de dragón"),
    BEETROOT_SOUP("sopa de remolacha"),
    BEETROOT_SEEDS("semillas"),
    BEETROOT("remolacha"),
    CHORUS_FRUIT_POPPED("chorus"),
    CHORUS_FRUIT("chorus"),
    END_CRYSTAL("cristal del end"),
    COOKED_MUTTON("cordero cocinado"),
    MUTTON("cordero"),
    COMMAND_MINECART("minecart"),
    COOKED_RABBIT("conejo cocinado"),
    SLIME_BALL("bola de slime"),
    STRUCTURE_BLOCK("estructura"),
    CONCRETE_POWDER("cemento"),
    CONCRETE("cemento"),
    OBSERVER("observador"),
    STRUCTURE_VOID("estructura"),
    BONE_BLOCK("bloque de hueso"),
    RED_NETHER_BRICK("ladrillos rojos"),
    NETHER_WART_BLOCK("verruga"),
    MAGMA("bloque de magma"),
    FROSTED_ICE("hielo compacto"),
    COMMAND_CHAIN("comandos"),
	COMMAND_REPEATING("comandos"),
	END_GATEWAY("transmisor"),
	GRASS_PATH("camino"),
	BEETROOT_BLOCK("remolacha"),
	PURPUR_DOUBLE_SLAB("losa doble"),
	PURPUR_STAIRS("escaleras"),
	CHORUS_FLOWER("flor chorus"),
	CHORUS_PLANT("planta chorus"),
	END_ROD("vara del end"),
	DAYLIGHT_DETECTOR_INVERTED("detector nocturno"),
	DOUBLE_PLANT("planta doble"),
	PACKED_ICE("hielo compacto"),
	STATIONARY_WATER("agua estática"),
	IRON_TRAPDOOR("trampilla de hierro"),
	PISTON_STICKY_BASE("pistón pegajoso"),
    WHITE_SHULKER_BOX("caja de shulker"),
    ORANGE_SHULKER_BOX("caja de shulker"),
    MAGENTA_SHULKER_BOX("caja de shulker"),
    LIGHT_BLUE_SHULKER_BOX("caja de shulker"),
    YELLOW_SHULKER_BOX("caja de shulker"),
    LIME_SHULKER_BOX("caja de shulker"),
    PINK_SHULKER_BOX("caja de shulker"),
    GRAY_SHULKER_BOX("caja de shulker"),
    SILVER_SHULKER_BOX("caja de shulker"),
    CYAN_SHULKER_BOX("caja de shulker"),
    PURPLE_SHULKER_BOX("caja de shulker"),
    BLUE_SHULKER_BOX("caja de shulker"),
    BROWN_SHULKER_BOX("caja de shulker"),
    GREEN_SHULKER_BOX("caja de shulker"),
    RED_SHULKER_BOX("caja de shulker"),
    BLACK_SHULKER_BOX("caja de shulker"),
    WHITE_GLAZED_TERRACOTTA("terracota #1"),
    ORANGE_GLAZED_TERRACOTTA("terracota #2"),
    MAGENTA_GLAZED_TERRACOTTA("terracota #3"),
    LIGHT_BLUE_GLAZED_TERRACOTTA("terracota #4"),
    YELLOW_GLAZED_TERRACOTTA("terracota #5"),
    LIME_GLAZED_TERRACOTTA("terracota #6"),
    PINK_GLAZED_TERRACOTTA("terracota #7"),
    GRAY_GLAZED_TERRACOTTA("terracota #8"),
    SILVER_GLAZED_TERRACOTTA("terracota #9"),
    CYAN_GLAZED_TERRACOTTA("terracota #10"),
    PURPLE_GLAZED_TERRACOTTA("terracota #11"),
    BLUE_GLAZED_TERRACOTTA("terracota #12"),
    BROWN_GLAZED_TERRACOTTA("terracota #13"),
    GREEN_GLAZED_TERRACOTTA("terracota #14"),
    RED_GLAZED_TERRACOTTA("terracota #15"),
    BLACK_GLAZED_TERRACOTTA("terracota #16"),
    
    
    ;

	private static final Map<String, ItemNameUtils> lookup = new HashMap<String, ItemNameUtils>();
	
    private final String name;

    private ItemNameUtils(final String name){
        this.name = name;
    }

    public String toString(){
        return name;
    }
    
    public static ItemNameUtils getMaterialName(Material material){
    	
    	if(lookup.size() <= 0)
    		for(ItemNameUtils itemName : values())
    			lookup.put(itemName.name(), itemName);
    	
        ItemNameUtils result = lookup.get(material.name());
        
        if(result == null)
        	result = ItemNameUtils.UNKNOW;
        
        return result;
    }
   
    public String firstUpperCased(){
        char first = Character.toUpperCase(name.charAt(0));
        return first + name.substring(1);
    }
   
    public String firstAllUpperCased(){
        return WordUtils.capitalizeFully(name);
    }

    public String allUpperCased(){
        return name.toUpperCase();
    }
    
}
